[package]
name = "dt8852"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
chrono = "0.4.42"
clap = { version = "4.5.54", features = ["derive"] }
csv = "1.4.0"
serialport = "4.8.1"
thiserror = "2.0.17"
